Homepage alpin
saepasomba/flight-booking-react pull request #2
Opened 2022-11-25 10:32 UTC by alpinmohsa541

**Changes**

create header
create homepage
create a column search schedule
create a calendar in the flight schedule search column

**Todo**
Responsive
Create a class column in the schedule search field

**Preview**
Tampilan  Dekstop
![image](https://user-images.githubusercontent.com/55131607/203962617-2a56d9f1-4dfc-4d86-a839-8cde947fdf79.png)
Tampilan Calender di bagian pencarian jadwal penerbangan
![image](https://user-images.githubusercontent.com/55131607/203963842-9b124238-3b19-4441-b8a1-e8b999b4cacd.png)
Tampilan jumlah penumpang dan jenis penumpang
![image](https://user-images.githubusercontent.com/55131607/203963975-fe164b1e-cd05-4f55-a5f9-c6b8c692e342.png)

2022-11-25 12:10 UTC, saepasomba requested changes
Berhubung diliat-liat masnya make pure HTML CSS, saya saranin pake CSS module [(link)](https://css-tricks.com/css-modules-part-1-need/) ** Bisa cek resource lain. Ini supaya class name nya gak tabrakan sama module / CSS framework lain.

2022-11-25 12:10 UTC, saepasomba commented on src/pages/Homepage/Homepage.js
> +    </div>
Indentasinya

2022-11-25 12:10 UTC, saepasomba commented on src/index.js
> +          <Route path='/' element={<Header />} />
Mungkin ini ke Homepage?

2022-11-25 12:10 UTC, saepasomba commented on src/components/navbar/Navbar.js
> +        </div>
Indentasinya

2022-11-27 10:42 UTC, alpinmohsa541 commented
> Berhubung diliat-liat masnya make pure HTML CSS, saya saranin pake CSS module [(link)](https://css-tricks.com/css-modules-part-1-need/) ** Bisa cek resource lain. Ini supaya class name nya gak tabrakan sama module / CSS framework lain.

2022-11-27 10:42 UTC, closed without merging